name: 960 Base
description: A base 960.gs theme, suitable for extending
author: Andrew Gruner
link: http://nodepub.com
version: 0.1
required_npub_version: 0.5
highest_npub_version: 0.5
first_releasedate: 2013-04-27
latest_releasedate: 2013-04-27

stylesheets:
  - 960.min.css
  - theme.css

settings:
  body_bg_color: '#fff'
  body_font: '"HelveticaNeue", "Helvetica Neue", Helvetica, Arial, sans-serif'
  body_font_color: '#000'
  heading_font_color: '#181818'
  heading_font: '"Georgia", "Times New Roman", serif'
  header_bg_color: '#666'
  header_font_color: '#fff'
  footer_bg_color: '#333'
  footer_font_color: '#fff'