name: Skeleton Base
description: A simple responsive theme, suitable for extending
author: Andrew Gruner
link: http://nodepub.com
version: 0.1
required_npub_version: 0.5
highest_npub_version: 0.5
first_releasedate: 2012-11-10
latest_releasedate: 2012-11-10

stylesheets:
  - base.css
  - skeleton.css
  - layout.css
  - theme.css

# each key suffix indicates its type
# possible types are _color, _font, _image
# should these be form types?
# should there be a font stack provider?
# maybe each theme could include font stacks? and we can collect them all?
# how to integrate TypeKit?
settings:
  body_bg_color: '#fff'
  body_font: '"HelveticaNeue", "Helvetica Neue", Helvetica, Arial, sans-serif'
  body_font_color: '#000'
  heading_font_color: '#181818'
  heading_font: '"Georgia", "Times New Roman", serif'
  header_bg_color: '#666'
  header_font_color: '#fff'
  footer_bg_color: '#333'
  footer_font_color: '#fff'