name: NodePub Admin
description: Default NodePub Administration Theme
author: Andrew Gruner
link: http://nodepub.com
version: 0.5
required_npub_version: 0.5
highest_npub_version: 0.5
first_releasedate: 2013-05-24
latest_releasedate: 2013-05-24

stylesheets:
  - //netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"
  - np_admin.css

javascripts:
  - require.js

settings:
  main_color: '#414141'
  accent_color: '#66ff66'